name: fitnestx
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  convex_bottom_bar: ^3.2.0
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^30.1.41
  syncfusion_flutter_calendar: ^30.1.41
  air_quality: ^4.1.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  cupertino_icons: ^1.0.8
  adaptive_theme: ^3.7.0
  image_picker: ^1.1.2
  table_calendar: ^3.0.9
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
